#!/usr/bin/env sh
set -eu

SRC_DIR="${1:-src}"
COMB_DIR="${2:-comb}"
OUT_ARCHIVE="${3:-comb.tar.br}"
SRC_COMBINED="${SRC_DIR}/combined.js"
COMB_RAW_JS="${COMB_DIR}/combined.raw.js"
COMB_JS="${COMB_DIR}/combined.js"
COMB_INDEX="${COMB_DIR}/index.html"
COMB_STYLE="${COMB_DIR}/styles.css"

if [ ! -d "${SRC_DIR}" ]; then
  echo "Source directory not found: ${SRC_DIR}" >&2
  exit 1
fi

if [ ! -f "${SRC_DIR}/index.html" ]; then
  echo "Missing ${SRC_DIR}/index.html" >&2
  exit 1
fi

if [ ! -f "${SRC_DIR}/styles.css" ]; then
  echo "Missing ${SRC_DIR}/styles.css" >&2
  exit 1
fi

mkdir -p "${COMB_DIR}"

MODULE_LIST="$(mktemp)"
TAR_LIST="$(mktemp)"
cleanup() {
  rm -f "${MODULE_LIST}" "${TAR_LIST}"
}
trap cleanup EXIT INT TERM

# Build a deterministic module order so combined.js can be generated
# even when src/index.html only loads ./combined.js.
printf '%s\n' "framework-core.js" > "${MODULE_LIST}"
find "${SRC_DIR}" -maxdepth 1 -type f -name 'minigame-*.js' -exec basename {} \; | sort >> "${MODULE_LIST}"
printf '%s\n' "minigames.js" >> "${MODULE_LIST}"
printf '%s\n' "app.js" >> "${MODULE_LIST}"

while IFS= read -r js_file; do
  if [ ! -f "${SRC_DIR}/${js_file}" ]; then
    echo "Missing required module: ${SRC_DIR}/${js_file}" >&2
    exit 1
  fi
done < "${MODULE_LIST}"

{
  echo "// Auto-generated by build_comb.sh."
  while IFS= read -r js_file; do
    echo
    echo "/* ===== ${js_file} ===== */"
    cat "${SRC_DIR}/${js_file}"
    echo
  done < "${MODULE_LIST}"
} > "${COMB_RAW_JS}"

if command -v terser >/dev/null 2>&1; then
  terser "${COMB_RAW_JS}" \
    -c passes=3,toplevel=true,ecma=2020 \
    -m toplevel=true \
    --mangle-props regex=/^_/ \
    --comments false \
    -o "${COMB_JS}"
else
  cp "${COMB_RAW_JS}" "${COMB_JS}"
  echo "Warning: terser not found; wrote unminified ${COMB_JS}" >&2
fi

rm -f "${COMB_RAW_JS}"

# Keep src/combined.js in sync so compress.sh and runtime use the latest bundle.
cp "${COMB_JS}" "${SRC_COMBINED}"

cp "${SRC_DIR}/index.html" "${COMB_INDEX}"
cp "${SRC_DIR}/styles.css" "${COMB_STYLE}"

printf '%s\n' "index.html" > "${TAR_LIST}"
printf '%s\n' "combined.js" >> "${TAR_LIST}"
printf '%s\n' "styles.css" >> "${TAR_LIST}"

# Copy non-JS assets from src/ to comb/, preserving paths.
find "${SRC_DIR}" -type f ! -name '*.js' ! -name 'index.html' ! -name 'styles.css' | while IFS= read -r src_file; do
  rel="${src_file#${SRC_DIR}/}"
  dst="${COMB_DIR}/${rel}"
  mkdir -p "$(dirname "${dst}")"
  cp "${src_file}" "${dst}"
  printf '%s\n' "${rel}" >> "${TAR_LIST}"
done

node --check "${SRC_COMBINED}"

tar --format ustar -cf - -C "${COMB_DIR}" -T "${TAR_LIST}" | brotli -q 11 -w 24 > "${OUT_ARCHIVE}"

echo "Build complete:"
echo "  Source bundle : ${SRC_COMBINED}"
echo "  Combined JS   : ${COMB_JS}"
echo "  Entry HTML    : ${COMB_INDEX}"
echo "  Archive       : ${OUT_ARCHIVE}"
stat -f "  Archive size  : %z bytes" "${OUT_ARCHIVE}"
